version: '3.6'
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
    env_file:
      - influxv2.env
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ../history.lp:/tmp/history.lp:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: unless-stopped
    env_file:
      - influxv2.env
    ports:
      - '8086:8086'
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      
volumes:
  grafana_data:
  influxdbv2: